SELECT CMF.HIERARCHY_ID, P.PARENT_ACCOUNT_NO, P.ELEMENT_ID, P.PARENT_SUBSCR_NO, P.COMPONENT_ID,
C.DESCRIPTION_CODE, D.DESCRIPTION_TEXT, E.EXTERNAL_ID GSM, E2.EXTERNAL_ID IMSI, TX_COMPANY COMPANYNAME
, ID_VPN, ID_USER NUMBER_NAME, IN_STATUS
FROM PRODUCT P, PRODUCT_ELEMENTS C, DESCRIPTIONS D, EXTERNAL_ID_EQUIP_MAP E
, CMF, component_definition_ref CDREF, EXTERNAL_ID_EQUIP_MAP E2
, VPN_CORP
WHERE P.ELEMENT_ID= C.ELEMENT_ID AND C.DESCRIPTION_CODE= D.DESCRIPTION_CODE AND D.LANGUAGE_CODE=1
AND P.PARENT_SUBSCR_NO= E.SUBSCR_NO AND E.EXTERNAL_ID_TYPE IN (11,40)
AND CMF.ACCOUNT_NO = P.PARENT_ACCOUNT_NO
AND CMF.DATE_ACTIVE < SYSDATE
AND (CMF.DATE_INACTIVE IS NULL OR CMF.DATE_INACTIVE > SYSDATE)
AND CDREF.INACTIVE_DT IS NULL
AND P.COMPONENT_ID BETWEEN 800 AND 802
AND CDREF.COMPONENT_ID = P.COMPONENT_ID  
AND P.PARENT_SUBSCR_NO=E2.SUBSCR_NO
AND E2.ACTIVE_DATE < SYSDATE
AND (E2.INACTIVE_DATE IS NULL OR E2.INACTIVE_DATE > SYSDATE)
AND E2.EXTERNAL_ID_TYPE IN (10)
AND VPN_CORP.in_status IN ('I','U','D' )
AND VPN_CORP.NU_CUENTA = CMF.HIERARCHY_ID
AND VPN_CORP.NU_MSISDN = E.EXTERNAL_ID
 



